version: "3.8"
services:
  postgres-db:
    image: postgres:latest
    restart: always
    volumes:
      - ./postgres-milkstgo-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: "tingeso2023"
    ports:
      - "5432:5432"
  app:
    container_name: milkstgo-app
    image: jovannischneider/milkstgo-app:latest
    ports:
      - "8090:8090"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres-db:5432/postgres?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=password
    deploy:
      restart_policy:
        condition: on-failure
    depends_on:
      - postgres-db